name: Android Build
on:
  push:
    branches: [ "main", "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v7


      - name: Set up JDK 17
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '17'



      - name: Setup Android SDK
        uses: android-actions/setup-android@v4


      - name: Install Android NDK
        run: |
          sdkmanager --install "ndk;29.0.14206865"


      - name: Configure CMake and Generate Android Project files
        working-directory: ./tests/android-compile-test/
        run: cmake -B build -DCOMPILE_ONLY_FOR_ANDROID=ON -DTHE_ENGINE_BUILD_TESTS=OFF


      - name: Grant execute permission for gradlew
        run: chmod +x ./tests/android-compile-test/android/gradlew

      - name: Build the Android Project
        working-directory: ./tests/android-compile-test/android/
        run: ./gradlew --no-daemon build
